[database]
host=
port=5432
name=musicbrainz
user=musicbrainz
password=musicbrainz
admin_user=postgres
admin_password=postgres

[musicbrainz]
base_url=https://metabrainz.org/api/musicbrainz/
# token=XXX

[tables]
ignore=isrc,iswc,artist_ipi,artist_isni,recording_isrc,label,label_*,l_*,l_artist_*,l_recording_*,work,work_*,place,place_*,area,area_*,url,url_*,editor,editor_*,medium,medium_*,annotation,vote,rating_raw,link,link_*,link,link_attribute,link_attribute_type,link_creditable_attribute_type,link_text_attribute_type,link_type,link_type_attribute_type,orderable_link_type,l_artist_recording,l_artist_artist,l_recording_recording

[schemas]
musicbrainz=musicbrainz
statistics=statistics
cover_art_archive=cover_art_archive
event_art_archive=event_art_archive
wikidocs=wikidocs
documentation=documentation
dbmirror2=dbmirror2
ignore=dbmirror2,documentation,wikidocs,event_art_archive,cover_art_archive,statistics
